# 基本は github.com のレポジトリーを指定するだけ
[[plugins]]
repo = 'Shougo/dein.vim'

#かっこよく
[[plugins]]
repo    = 'vim-airline/vim-airline'
depends = ['vim-airline-themes']

#見やすく
[[plugins]]
repo = 'vim-airline/vim-airline-themes'

#インデント可視化
#[[plugins]]
#repo = 'Yggdroot/indentLine'

#ctrl+p でファイルあいまい検索ができる
#[[plugins]]
#repo = 'ctrlpvim/ctrlp.vim'

#入力補完ctrl + k で次の入力するところに飛べる
[[plugins]]
repo = 'Shougo/neocomplcache'

# スニペットの補完機能
[[plugins]]
repo = 'Shougo/neosnippet'

# スニペット集
[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# fで検索後移動できるようにする
[[plugins]]
repo = 'rhysd/clever-f.vim'

# 気分によってcolorschemeかえる
[[plugins]]
repo = 'flazz/vim-colorschemes'

#プラグインによってjsonの表示がおかしくなるものがあるため入れる
[[plugins]]
repo = 'elzr/vim-json'

#ノードツリーとひらく デフォルトはctl + n
[[plugins]]
repo = 'scrooloose/nerdtree'

#gitで管理してる場合、左側に差分を表示
[[plugins]]
repo = 'airblade/vim-gitgutter'

#インデント可視化
[[plugins]]
repo = 'nathanaelkane/vim-indent-guides'

#:Gdiffと打つとHEADと現在の状態を比較できる
#:Glog = git log
#:Gdiff コミット番号でそのdiffをとれる
#:Gblameでコミット詳細みれる
#:Gstatus = git status
#:Gwrite [path]
#:Gcommit
#:Gdiff [fugitive-revision]
#:Gedit [fugitive-revision]
#:Gmove [destination]
#:Gremove
#:Glog [args]
#:Gpush [args]
#:Gfetch [args]
#:Gmerge [args]
#:Gpull [args]
[[plugins]]
repo = 'tpope/vim-fugitive'
